### ISSUE TITLE
Hit me up on linked in, I want to talk to you.

### ISSUE THREAD

**Issue by Vyom-Yadav** [SparkScratch-P/SparkScratch-P#2]
https://www.linkedin.com/in/vyom-yadav-66a97918b/, profile mein bhi link h
I basically want to ask if you are interested in making any project, I can handle backed with spring+hibernate and other sources if you are interested hmu.

**Comment by SparkScratch-P** [comment]
Bhai, I am new to Linked In, I mean, just opened the account now, Can u pls say,  where to write it? Where can I connect to u? And yes, I am not gonna buy Premium. Any other way?

 Or CHeck out my website; choose a way to connect to me. See, there, scroll down to the bottom, and there are comments. U can write there. [Note: Your email ID is hidden, no one, including me can see that, Feel free to write there.]
 
 ## My Website: [sparkscratch-p.github.io/](https://sparkscratch-p.github.io/)

**Comment by Vyom-Yadav** [comment]
Bhai tera discord link broken h, https://www.linkedin.com/in/prodyumna-pal-456a1622b/ agar ye tera linked in h to mene connection request bheje h, linked in thoda alag h, pehle aapke certain connections hone chahiye koi bhe profile view krne ke lie
